import {productImageUrl} from './image-assets';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Link,NavLink,useLocation,useNavigate} from 'react-router-dom';
import {ArrowUpRight,ArrowRight,Check,ChevronDown,ChevronRight,Grid2X2,Heart,MapPin,Menu,MessageCircle,Minus,Plus,Search,ShoppingCart,Truck,UserRound,X,PackageCheck,ShieldCheck,FileText,Settings,Mail,Box} from 'lucide-react';
import {categories,matches,money,type Product} from './data';
import {useStore} from './store';
import {flyToCart} from './motion';
import {getProductModel} from './product-model';
export function Logo(){return <Link to="/" className="logo" aria-label="КАМДЕТАЛЬ — главная"><span className="logo-symbol"><i/><i/><i/></span><span>КАМ<span className="logo-light">ДЕТАЛЬ</span><small>ЗАПЧАСТИ ДЛЯ БОЛЬШОЙ РАБОТЫ</small></span></Link>;}
export function ButtonLink({to,children,secondary=false}:{to:string;children:ReactNode;secondary?:boolean}){return <Link className={`btn ${secondary?'btn-secondary':''}`} to={to}>{children}<ArrowUpRight size={18}/></Link>;}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();const prev=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=prev;};},[]);
 return <dialog ref={ref} aria-label={title} className="modal" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={onClose} aria-label="Закрыть"><X/></button></div>{children}</dialog>;
}
export function Header(){
 const {cart,favorites,products,city,setCity,setRequest}=useStore();const [query,setQuery]=useState('');const [focused,setFocused]=useState(false);const [menu,setMenu]=useState(false);const [cityOpen,setCityOpen]=useState(false);const navigate=useNavigate();const location=useLocation();
 useEffect(()=>{setMenu(false);setFocused(false);},[location]);
 const found=query.trim()?products.filter(p=>matches(p,query)).slice(0,5):[];
 const count=cart.reduce((a,b)=>a+b.qty,0);
 return <><div className="topbar"><div className="container topbar-inner"><button onClick={()=>setCityOpen(true)}><MapPin size={13}/>{city}<ChevronDown size={12}/></button><span className="topbar-shipping">Запчасти для вашего дела. Доставка по России.</span><span className="demo-label"><span/> Демо-магазин</span></div></div>
 <header className="header"><div className="container header-main"><Logo/><div className="header-search"><form role="search" onSubmit={e=>{e.preventDefault();navigate(`/catalog?q=${encodeURIComponent(query.trim())}`);setFocused(false);}}><Search size={20}/><input aria-label="Поиск по названию, артикулу или OEM" placeholder="Название детали, артикул или OEM-номер" value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>setFocused(true)} onKeyDown={e=>{if(e.key==='Escape')setFocused(false);}}/><button aria-label="Найти запчасть" type="submit"><ArrowRight size={20}/></button></form>{focused&&query.trim()&&<><button className="search-dismiss" aria-label="Закрыть подсказки" onClick={()=>setFocused(false)}/><div className="search-results">{found.length?found.map(p=><Link key={p.id} to={`/product/${p.id}`}><img src={productImageUrl(p.image)} alt=""/><span>{p.name}<small>{p.article}</small></span><b>{money(p.price)}</b></Link>):<p>Не нашли деталь. Попробуйте другой артикул.</p>}<Link className="search-all" to={`/catalog?q=${encodeURIComponent(query)}`}>Все результаты <ArrowRight size={16}/></Link></div></>}</div><div className="header-actions"><Link to="/favorites" className="header-action" aria-label="Избранное"><span><Heart/>{favorites.length>0&&<em>{favorites.length}</em>}</span><small>Избранное</small></Link><Link to="/account" className="header-action" aria-label="Личный кабинет"><UserRound/><small>Кабинет</small></Link><Link to="/cart" className="header-action cart-action" aria-label={`Корзина, ${count} товаров`}><span><ShoppingCart/>{count>0&&<em>{count}</em>}</span><small>Корзина</small></Link></div></div>
 <div className="nav-border"><nav className="container nav"><button className={`catalog-toggle ${menu?'is-active':''}`} onClick={()=>setMenu(!menu)} aria-expanded={menu}><Menu size={20}/>Каталог запчастей<ChevronDown size={16}/></button><NavLink to="/catalog?stock=1">В наличии</NavLink><NavLink to="/delivery">Доставка и оплата</NavLink><NavLink to="/guarantee">Гарантия и возврат</NavLink><NavLink to="/about">О компании</NavLink><button className="nav-consult" onClick={()=>setRequest({title:'Помощь с подбором'})}><MessageCircle size={17}/>Помощь с подбором <ArrowUpRight size={14}/></button></nav></div>
 {menu&&<><button className="mega-backdrop" aria-label="Закрыть каталог" onClick={()=>setMenu(false)}/><div className="mega-menu container"><div className="mega-heading"><h2>Каталог запчастей</h2><Link to="/catalog">Смотреть всё <ArrowRight size={18}/></Link></div><div className="mega-grid">{categories.map(c=><div key={c.id}><Link to={`/catalog?category=${c.id}`} className="mega-category"><img src={productImageUrl(c.image)} alt=""/>{c.name}<ChevronRight size={16}/></Link>{c.subs.map(s=><Link key={s} to={`/catalog?category=${c.id}&sub=${encodeURIComponent(s)}`}>{s}</Link>)}</div>)}</div></div></>}
 </header>{cityOpen&&<Modal title="Ваш город" onClose={()=>setCityOpen(false)}><p className="muted">Город используется при оформлении доставки.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setCity(String(f.get('city')).trim());setCityOpen(false);}}><label>Название города<input name="city" required defaultValue={city} maxLength={80}/></label><button className="btn full">Сохранить город<Check size={18}/></button></form><div className="city-options">{['Москва','Санкт-Петербург','Казань','Набережные Челны','Екатеринбург'].map(c=><button key={c} onClick={()=>{setCity(c);setCityOpen(false);}}>{c}</button>)}</div></Modal>}</>;
}
export function Breadcrumb({items}:{items:{label:string;to?:string}[]}){return <nav className="breadcrumbs" aria-label="Хлебные крошки"><Link to="/">Главная</Link>{items.map((i,index)=><span key={index}><ChevronRight size={12}/>{i.to?<Link to={i.to}>{i.label}</Link>:<span aria-current="page">{i.label}</span>}</span>)}</nav>;}
export function SectionHeading({eyebrow,title,to,link='Смотреть все'}:{eyebrow?:string;title:string;to?:string;link?:string}){return <div className="section-heading"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{to&&<Link className="text-link" to={to}>{link}<ArrowUpRight size={18}/></Link>}</div>;}
export function ProductCard({product:p}:{product:Product}){const {favorites,toggleFavorite,addToCart,cart}=useStore();const added=cart.some(l=>l.id===p.id);return <article className="product-card"><div className="product-image"><Link to={`/product/${p.id}`}><img src={productImageUrl(p.image)} alt={p.name} loading="lazy"/></Link>{p.badge&&<span className="product-badge">{p.badge}</span>}{getProductModel(p.id)&&<span className="product-3d-badge" title="Доступна AI-реконструкция по фото"><Box size={13}/>3D</span>}<button className={`favorite-btn ${favorites.includes(p.id)?'selected':''}`} onClick={()=>toggleFavorite(p.id)} aria-label={`${favorites.includes(p.id)?'Убрать из избранного':'В избранное'}: ${p.name}`}><Heart size={19}/></button></div><div className="product-content"><div className="product-meta"><span>{p.brand}</span><span>{p.article}</span></div><Link to={`/product/${p.id}`} className="product-name">{p.name}</Link><span className={`stock ${p.stock?'':'on-order'}`}><span/>{p.stock?`В наличии · ${p.stock} шт.`:'Под заказ'}</span><div className="product-bottom"><strong>{money(p.price)}</strong><button className={`add-btn ${added?'added':''}`} onClick={e=>{addToCart(p.id);flyToCart(e.currentTarget,p.image);}} aria-label={`В корзину: ${p.name}`}>{added?<Check size={19}/>:<Plus size={21}/>}</button></div></div></article>;}
export function Quantity({value,onChange}:{value:number;onChange:(n:number)=>void}){return <div className="quantity"><button aria-label="Уменьшить количество" disabled={value<=1} onClick={()=>onChange(Math.max(1,value-1))}><Minus size={15}/></button><input aria-label="Количество" type="number" min={1} max={999} value={value} onChange={e=>onChange(Math.max(1,Math.min(999,Number(e.target.value)||1)))}/><button aria-label="Увеличить количество" disabled={value>=999} onClick={()=>onChange(Math.min(999,value+1))}><Plus size={15}/></button></div>;}
export function EmptyState({title,text,icon='cart'}:{title:string;text:string;icon?:string}){return <div className="empty-state"><span>{icon==='heart'?<Heart size={35}/>:<ShoppingCart size={35}/>}</span><h2>{title}</h2><p>{text}</p><ButtonLink to="/catalog">Перейти в каталог</ButtonLink></div>;}
export function TrustStrip(){return <div className="trust-strip">{[{icon:PackageCheck,title:'Всё для вашего КАМАЗ',text:'Подбор по модели и артикулу'},{icon:Truck,title:'Доставка по России',text:'СДЭК и самовывоз'},{icon:FileText,title:'Удобно для бизнеса',text:'Заказ с выставлением счёта'},{icon:ShieldCheck,title:'Проверка перед оплатой',text:'Менеджер подтвердит наличие'}].map(({icon:Icon,title,text})=><div key={title}><Icon size={26} strokeWidth={1.5}/><span><b>{title}</b><small>{text}</small></span></div>)}</div>;}
export function Footer(){const {setRequest}=useStore();return <footer className="footer"><div className="container"><div className="footer-v2-cta"><div><span className="section-marker"><i/>РАБОТА ДОЛЖНА ПРОДОЛЖАТЬСЯ</span><h2>СЛЕДУЮЩАЯ ОСТАНОВКА —<br/><span>ВАША МАСТЕРСКАЯ.</span></h2></div><button className="footer-circle-cta" onClick={()=>setRequest({title:'Подобрать запчасти'})} aria-label="Подобрать запчасти"><ArrowUpRight size={38}/></button></div><div className="footer-main"><div><Logo/><p>Большой технике — надёжные детали.<br/>Вашему делу — уверенное движение.</p><span className="footer-note">Концепция магазина · демонстрационные данные</span></div><div><h4>Покупателям</h4><Link to="/delivery">Доставка и оплата</Link><Link to="/guarantee">Гарантия и возврат</Link><Link to="/account">Личный кабинет</Link><Link to="/favorites">Избранное</Link></div><div><h4>Каталог</h4>{categories.slice(0,4).map(c=><Link key={c.id} to={`/catalog?category=${c.id}`}>{c.name}</Link>)}</div><div className="footer-help"><h4>Нужна помощь?</h4><p>Подберём детали под вашу задачу.</p><button onClick={()=>setRequest({title:'Связаться со специалистом'})}>Связаться со специалистом<ArrowUpRight size={17}/></button><Link to="/contacts"><Mail size={15}/> Контакты и реквизиты</Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} КАМДЕТАЛЬ. Концепция независимого магазина.</span><Link to="/privacy">Политика конфиденциальности</Link><Link to="/admin"><Settings size={13}/> Управление демо</Link></div></div></footer>;}
export function RequestModal(){const {request,setRequest}=useStore();const [saved,setSaved]=useState(false);useEffect(()=>setSaved(false),[request]);if(!request)return null;return <Modal title={request.title} onClose={()=>setRequest(null)}>{saved?<div className="request-success"><span><Check size={30}/></span><h3>Заявка сохранена в демо</h3><p>Это прототип: данные остались в вашем браузере и не отправлены менеджеру.</p><button className="btn full" onClick={()=>setRequest(null)}>Понятно</button></div>:<><p className="muted">{request.product?request.product.name:'Укажите телефон и задачу — это поможет специалисту с подбором.'}</p><form onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));try{const prev=JSON.parse(localStorage.getItem('kamdetal.requests.v1')||'[]');localStorage.setItem('kamdetal.requests.v1',JSON.stringify([...prev,{...data,product:request.product?.id,date:new Date().toISOString()}]));setSaved(true);}catch{alert('Не удалось сохранить заявку. Проверьте доступ к хранилищу браузера.');}}}><label>Ваше имя<input name="name" placeholder="Как к вам обращаться" required maxLength={80}/></label><label>Телефон<input name="phone" type="tel" placeholder="+7 (___) ___-__-__" required pattern={'[+0-9\\s\\(\\)\\-]{10,20}'}/></label><label>Что нужно подобрать?<textarea name="message" defaultValue={request.message||''} rows={3} placeholder="Артикул, модель автомобиля или VIN" maxLength={1000}/></label><label className="checkbox"><input type="checkbox" required/>Согласен на обработку данных в этой демоверсии</label><button className="btn full">{request.product?'Сохранить заказ в 1 клик':'Сохранить заявку'}<ArrowRight size={18}/></button><p className="form-note">Демо: заявка сохраняется только в этом браузере.</p></form></>}</Modal>;}
export function MobileNav(){const {cart}=useStore();return <nav className="mobile-nav"><NavLink to="/" end><Grid2X2 size={20}/><span>Главная</span></NavLink><NavLink to="/catalog"><Menu size={20}/><span>Каталог</span></NavLink><NavLink to="/cart"><ShoppingCart size={20}/><span>Корзина {cart.length>0&&`(${cart.reduce((a,b)=>a+b.qty,0)})`}</span></NavLink><NavLink to="/account"><UserRound size={20}/><span>Кабинет</span></NavLink></nav>;}
